"""
Merged Chapter 3 visualization script for paper Figures 7-12.

All experiment values are loaded from chapter3_experiment_data.json, which is
generated by generate_chapter3_data.py from the CleVer experiment model.
"""

from __future__ import annotations

import json
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import font_manager
from matplotlib.patches import Patch
from matplotlib.ticker import FuncFormatter, LogLocator, NullFormatter


COLORS = {
    "light_blue": "#90C9E7",
    "cyan_blue": "#219EBC",
    "dark_blue": "#136783",
    "navy": "#02304A",
    "gold": "#FEB705",
    "orange": "#FF9E02",
    "dark_orange": "#FA8600",
}

SCRIPT_DIR = os.path.dirname(__file__)
DATA_PATH = os.path.join(SCRIPT_DIR, "chapter3_experiment_data.json")
OUT_DIR = os.path.join(SCRIPT_DIR, "正确图片输出")
os.makedirs(OUT_DIR, exist_ok=True)

available_fonts = [f.name for f in font_manager.fontManager.ttflist]
preferred_fonts = [
    "Microsoft YaHei",
    "SimHei",
    "SimSun",
    "WenQuanYi Micro Hei",
    "Noto Sans CJK SC",
    "STHeiti",
    "PingFang SC",
    "Songti SC",
    "Heiti TC",
    "AR PL UMing CN",
    "DejaVu Sans",
]
usable_fonts = [f for f in preferred_fonts if f in available_fonts]
print("检测到可用字体：", usable_fonts if usable_fonts else ["DejaVu Sans"])

plt.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.sans-serif": usable_fonts if usable_fonts else ["DejaVu Sans"],
        "mathtext.fontset": "dejavusans",
        "axes.unicode_minus": False,
        "font.size": 10.5,
        "axes.labelsize": 10.5,
        "axes.titlesize": 10.5,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 8.5,
        "figure.dpi": 600,
        "savefig.dpi": 600,
        "savefig.bbox": "tight",
        "axes.grid": True,
        "grid.alpha": 0.3,
        "grid.linewidth": 0.5,
        "axes.edgecolor": "#333333",
        "axes.linewidth": 0.8,
    }
)


def load_data() -> dict:
    if not os.path.exists(DATA_PATH):
        from generate_chapter3_data import build_data

        with open(DATA_PATH, "w", encoding="utf-8") as f:
            json.dump(build_data(), f, ensure_ascii=False, indent=2)
            f.write("\n")
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


DATA = load_data()
TASK_NAMES = [item["name"] for item in DATA["tasks"]]
TASK_GAS = [item["gas"] for item in DATA["tasks"]]


def set_bottom_title(ax, title, fontsize=12.5, fontweight="bold"):
    ax.text(
        0.5,
        -0.23,
        title,
        transform=ax.transAxes,
        ha="center",
        va="top",
        fontsize=fontsize,
        fontweight=fontweight,
    )


def format_log_axis(ax):
    def formatter(value, _pos):
        if value <= 0:
            return ""
        exponent = int(np.round(np.log10(value)))
        if np.isclose(value, 1.0):
            return "1"
        return f"10^{exponent}"

    ax.yaxis.set_major_locator(LogLocator(base=10.0))
    ax.yaxis.set_major_formatter(FuncFormatter(formatter))
    ax.yaxis.set_minor_formatter(NullFormatter())


def savefig(fig, filename):
    fig.savefig(os.path.join(OUT_DIR, filename), dpi=600, bbox_inches="tight", pad_inches=0.1)
    plt.close(fig)


def fig_budget_compliance():
    fig, ax = plt.subplots(figsize=(9.5, 4.2))
    section = DATA["budget_compliance"]
    b_values = section["b_values"]
    alpha = section["alpha"]
    x = np.arange(len(TASK_NAMES))
    w = 0.16
    colors = [COLORS["light_blue"], COLORS["cyan_blue"], COLORS["dark_blue"], COLORS["gold"]]
    labels = ["$10^6$", "$10^7$", "$10^8$", "$10^9$"]

    for idx, (_b_value, color, label) in enumerate(zip(b_values, colors, labels)):
        positions = x + (idx - 1.5) * w
        values = [section["samples_percent"][task][f"{_b_value:.0f}"] for task in TASK_NAMES]
        box = ax.boxplot(
            values,
            positions=positions,
            widths=w * 0.86,
            patch_artist=True,
            showmeans=True,
            manage_ticks=False,
            whis=(0, 100),
            boxprops=dict(facecolor=color, alpha=0.82, edgecolor=COLORS["navy"], linewidth=0.8),
            medianprops=dict(color=COLORS["navy"], linewidth=1.2),
            meanprops=dict(marker="o", markerfacecolor="white", markeredgecolor=COLORS["dark_orange"], markersize=4),
            whiskerprops=dict(color="#555555", linewidth=0.8),
            capprops=dict(color="#555555", linewidth=0.8),
            flierprops=dict(marker=".", markerfacecolor=color, markeredgecolor=color, alpha=0.45, markersize=3),
        )
        box["boxes"][0].set_label(label)

    ax.axhline(y=100, color=COLORS["dark_orange"], linestyle="--", linewidth=1.2, alpha=0.8, label="预算上限")
    ax.axhline(y=alpha * 100, color="#888888", linestyle=":", linewidth=1.1, alpha=0.8, label=f"$\\alpha B$={alpha * 100:.0f}%")
    ax.set_title("不同任务与预算设置下的段预算满足情况", fontsize=10.5, fontweight="bold", pad=8)
    ax.set_xticks(x)
    ax.set_xticklabels(TASK_NAMES, fontsize=9)
    ax.set_xlabel("任务类型", fontsize=9.5)
    ax.set_ylabel("段权重占预算比例 $W(\\mathrm{Seg}_i)/B$（%）", fontsize=9.5)
    ax.set_ylim(0, 108)
    handles, legend_labels = ax.get_legend_handles_labels()
    unique = dict(zip(legend_labels, handles))
    ax.legend(unique.values(), unique.keys(), loc="lower center", bbox_to_anchor=(0.5, -0.28), ncol=6, fontsize=8.2, framealpha=0.95)
    fig.tight_layout()
    savefig(fig, "fig1_budget_compliance.png")
    print("  -> 图7/fig1_budget_compliance.png 已生成")


def fig_overhead():
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))
    section = DATA["slicing_overhead"]
    exec_times_no_slice = section["exec_times_no_slice"]
    exec_times_slice = section["exec_times_slice"]
    overhead_ratios = section["overhead_ratios"]
    x = np.arange(len(TASK_NAMES))
    w = 0.32

    ax1.bar(x - w / 2, exec_times_no_slice, w, label="未切片", color=COLORS["light_blue"], alpha=0.9, edgecolor=COLORS["navy"], linewidth=0.6)
    ax1.bar(x + w / 2, exec_times_slice, w, label="采用切片", color=COLORS["orange"], alpha=0.9, edgecolor=COLORS["dark_orange"], linewidth=0.6)
    for i, (t_s, ratio) in enumerate(zip(exec_times_slice, overhead_ratios)):
        ax1.annotate(f"$\\rho$={ratio * 100:.1f}%", xy=(x[i] + w / 2, t_s), xytext=(0, 6), textcoords="offset points", ha="center", fontsize=8.5, color=COLORS["navy"], fontweight="bold")
    ax1.set_yscale("log")
    ax1.set_xticks(x)
    ax1.set_xticklabels(TASK_NAMES, fontsize=9)
    ax1.set_ylabel("执行时间（秒）", fontsize=9.5)
    set_bottom_title(ax1, "（a）切片对执行时间的影响")
    ax1.legend(loc="upper left", fontsize=8.5, framealpha=0.9)
    ax1.set_ylim(5, 50000)
    format_log_axis(ax1)

    components = section["component_percent"]
    safecut = components["safecut"]
    snapshot = components["snapshot"]
    commitment = components["commitment"]
    ax2.bar(x, safecut, 0.5, label="SafeCut 检查", color=COLORS["light_blue"], alpha=0.9, edgecolor=COLORS["navy"], linewidth=0.6)
    ax2.bar(x, snapshot, 0.5, bottom=safecut, label="快照序列化", color=COLORS["gold"], alpha=0.9, edgecolor=COLORS["dark_orange"], linewidth=0.6)
    bottom2 = [s + n for s, n in zip(safecut, snapshot)]
    ax2.bar(x, commitment, 0.5, bottom=bottom2, label="承诺计算", color=COLORS["orange"], alpha=0.9, edgecolor=COLORS["dark_orange"], linewidth=0.6)
    totals = [s + n + c for s, n, c in zip(safecut, snapshot, commitment)]
    for i, total in enumerate(totals):
        ax2.text(x[i], total + 0.25, f"{total:.1f}%", ha="center", fontsize=9, fontweight="bold", color=COLORS["navy"])
    ax2.set_xticks(x)
    ax2.set_xticklabels(TASK_NAMES, fontsize=9)
    ax2.set_ylabel("开销比例 $\\rho$（%）", fontsize=9.5)
    set_bottom_title(ax2, "（b）开销构成分解")
    ax2.legend(loc="upper left", fontsize=8.5, framealpha=0.9)
    ax2.set_ylim(0, 13)
    fig.tight_layout(w_pad=2.5, rect=[0, 0.08, 1, 1])
    savefig(fig, "fig2_overhead.png")
    print("  -> 图8/fig2_overhead.png 已生成")


def plot_param_sensitivity(section_name, output_name, message):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
    section = DATA[section_name]
    b_vals = section["b_values"]
    b_labels = ["$10^6$", "$10^7$", "$10^8$", "$10^9$"]
    x1 = range(len(b_vals))
    color1, color2 = COLORS["cyan_blue"], COLORS["dark_orange"]
    ax1_twin = ax1.twinx()
    ln1 = ax1.plot(x1, section["snapshot_count"], "s-", color=color1, markersize=7, linewidth=2, markerfacecolor=COLORS["light_blue"], markeredgecolor=color1, markeredgewidth=1.5, label="快照数量 $m$", zorder=3)
    ln2 = ax1_twin.plot(x1, section["storage_mb"], "o--", color=color2, markersize=7, linewidth=2, markerfacecolor=COLORS["gold"], markeredgecolor=color2, markeredgewidth=1.5, label="存储开销（MB）", zorder=3)
    ax1.set_yscale("log")
    ax1_twin.set_yscale("log")
    ax1.set_xticks(list(x1))
    ax1.set_xticklabels(b_labels, fontsize=9)
    ax1.set_xlabel("段预算 $B$（Gas）", fontsize=9.5)
    ax1.set_ylabel("快照数量 $m$", fontsize=9.5, color=color1)
    ax1_twin.set_ylabel("链下存储开销（MB）", fontsize=9.5, color=color2)
    ax1.tick_params(axis="y", labelcolor=color1)
    ax1_twin.tick_params(axis="y", labelcolor=color2)
    set_bottom_title(ax1, "（a）段预算 $B$ 的影响\n（固定 $b = 10^6$，Sort-Large）")
    format_log_axis(ax1)
    format_log_axis(ax1_twin)
    lns = ln1 + ln2
    ax1.legend(lns, [line.get_label() for line in lns], loc="upper right", fontsize=8.5, framealpha=0.9)

    threshold_values = section["threshold_values"]
    threshold_labels = ["$10^4$", "$10^5$", "$10^6$", "$10^7$"]
    x2 = range(len(threshold_values))
    color3, color4 = COLORS["dark_blue"], COLORS["dark_orange"]
    ax2_twin = ax2.twinx()
    ln3 = ax2.plot(x2, section["subsegment_count"], "s-", color=color3, markersize=7, linewidth=2, markerfacecolor=COLORS["light_blue"], markeredgecolor=color3, markeredgewidth=1.5, label="子段数量 $L$", zorder=3)
    ln4 = ax2_twin.plot(x2, section["verseg_gas_k"], "o--", color=color4, markersize=7, linewidth=2, markerfacecolor=COLORS["gold"], markeredgecolor=color4, markeredgewidth=1.5, label="VerSeg Gas 开销（K Gas）", zorder=3)
    ax2.set_yscale("log")
    ax2_twin.set_yscale("log")
    ax2.set_xticks(list(x2))
    ax2.set_xticklabels(threshold_labels, fontsize=9)
    ax2.set_xlabel("裁决阈值 $b$（Gas）", fontsize=9.5)
    ax2.set_ylabel("子段数量 $L$", fontsize=9.5, color=color3)
    ax2_twin.set_ylabel("VerSeg Gas 开销（K Gas）", fontsize=9.5, color=color4)
    ax2.tick_params(axis="y", labelcolor=color3)
    ax2_twin.tick_params(axis="y", labelcolor=color4)
    set_bottom_title(ax2, "（b）裁决阈值 $b$ 的影响\n（固定 $B = 10^8$，Sort-Large）")
    format_log_axis(ax2)
    format_log_axis(ax2_twin)
    lns2 = ln3 + ln4
    ax2.legend(lns2, [line.get_label() for line in lns2], loc="center right", fontsize=8.5, framealpha=0.9)
    fig.tight_layout(w_pad=3, rect=[0, 0.10, 1, 1])
    savefig(fig, output_name)
    print(message)


def fig_gas_comparison():
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))
    section = DATA["gas_comparison"]
    schemes = section["schemes"]
    x = np.arange(len(schemes))
    w = 0.52
    bar_colors = [COLORS["light_blue"], COLORS["cyan_blue"], COLORS["gold"], COLORS["orange"], COLORS["dark_orange"]]
    opt_gas = section["optimistic_gas_k"]
    bars = ax1.bar(x, opt_gas, w, color=bar_colors, alpha=0.9, edgecolor=COLORS["navy"], linewidth=0.6)
    for bar, value in zip(bars, opt_gas):
        ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 5, f"{value:.0f}K", ha="center", va="bottom", fontsize=8.5, fontweight="bold", color=COLORS["navy"])
    ax1.set_xticks(x)
    ax1.set_xticklabels(schemes, fontsize=9)
    ax1.set_ylabel("链上 Gas 开销（K Gas）", fontsize=9.5)
    set_bottom_title(ax1, "（a）乐观路径（无争议）")
    ax1.set_ylim(0, 420)

    disp_gas = section["dispute_gas_k"]
    bars = ax2.bar(x, disp_gas, w, color=bar_colors, alpha=0.9, edgecolor=COLORS["navy"], linewidth=0.6)
    for bar, value in zip(bars, disp_gas):
        ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 80, f"{value:.0f}K", ha="center", va="bottom", fontsize=8.5, fontweight="bold", color=COLORS["navy"])
    avg_others = np.mean(disp_gas[:4])
    ax2.axhline(y=avg_others, color=COLORS["dark_blue"], linestyle="--", linewidth=1.2, alpha=0.6)
    reduction = (1 - disp_gas[4] / avg_others) * 100
    ax2.annotate(f"较平均值降低 {reduction:.0f}%", xy=(4, disp_gas[4]), xytext=(3.05, disp_gas[4] + 1800), fontsize=9.5, fontweight="bold", color=COLORS["dark_orange"], arrowprops=dict(arrowstyle="->", color=COLORS["dark_orange"], lw=1.5))
    ax2.set_xticks(x)
    ax2.set_xticklabels(schemes, fontsize=9)
    ax2.set_ylabel("链上 Gas 开销（K Gas）", fontsize=9.5)
    set_bottom_title(ax2, "（b）争议路径（Sort-Large，$W_{\\mathrm{total}} = 10^{11}$ Gas）")
    ax2.set_ylim(0, 6200)
    fig.tight_layout(w_pad=3, rect=[0, 0.08, 1, 1])
    savefig(fig, "fig_gas_comparison_v2.png")
    print("  -> 图10/fig_gas_comparison_v2.png 已生成")


def fig_staking_analysis():
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.8))
    section = DATA["staking_analysis"]
    belief_colors = [COLORS["light_blue"], COLORS["cyan_blue"], COLORS["dark_blue"], COLORS["gold"], COLORS["orange"], COLORS["dark_orange"]]
    beta_values = section["beta_values"]
    for p, color in zip(section["beliefs"], belief_colors):
        key = str(p)
        if key not in section["exit_rounds_by_belief"]:
            key = f"{float(p):.1f}"
        ax1.plot(beta_values, section["exit_rounds_by_belief"][key], "-", color=color, linewidth=1.8, label=f"$p = {p}$")
    ax1.set_xlabel("超线性指数 $\\beta$", fontsize=9.5)
    ax1.set_ylabel("预期退出轮数", fontsize=9.5)
    set_bottom_title(ax1, f"（a）预期退出轮数（$d_0 = {section['d0']}$）")
    ax1.legend(loc="upper right", fontsize=8, framealpha=0.9, title="失败信念概率 $p$", title_fontsize=8.5, ncol=2)
    ax1.set_ylim(0.5, section["g"] + 0.5)
    ax1.set_xlim(1.2, 3.0)
    ax1.set_yticks(range(1, section["g"] + 1))
    ax1.annotate("更高的 $p$ 或 $\\beta$\n意味着更早退出", xy=(1.8, 3.0), xytext=(2.3, 6.5), fontsize=9.5, fontweight="bold", color=COLORS["navy"], arrowprops=dict(arrowstyle="->", color=COLORS["navy"], lw=1.3), ha="center")

    rounds = section["rounds"]
    exit_payoff = section["exit_payoff"]
    ax2.plot(rounds, exit_payoff, "o-", color=COLORS["dark_blue"], linewidth=2.2, markersize=6, markerfacecolor=COLORS["light_blue"], label="退出收益 $-D(r)$", zorder=5)
    stay_styles = [("0.6", "--", COLORS["cyan_blue"], 1.8), ("0.8", "-.", COLORS["orange"], 1.8), ("1.0", ":", COLORS["dark_orange"], 2.0)]
    for p, linestyle, color, linewidth in stay_styles:
        stay_val = section["stay_payoff"][p]
        ax2.axhline(y=stay_val, linestyle=linestyle, color=color, linewidth=linewidth, label=f"坚持收益（$p = {p}$）: {stay_val:.0f}")
    stay_ref = section["stay_payoff"]["0.8"]
    exit_preferred = [r for r, payoff in zip(rounds, exit_payoff) if payoff > stay_ref]
    if exit_preferred:
        ax2.axvspan(min(exit_preferred) - 0.4, max(exit_preferred) + 0.4, alpha=0.15, color=COLORS["light_blue"], zorder=0)
        mid_r = np.mean(exit_preferred)
        ax2.text(mid_r, stay_ref + 4, "退出更优区域（$p=0.8$）", ha="center", fontsize=8.5, color=COLORS["dark_blue"], fontweight="bold")
    ax2.set_xlabel("质押轮次 $r$", fontsize=9.5)
    ax2.set_ylabel("期望收益（ETH）", fontsize=9.5)
    set_bottom_title(ax2, "（b）错误方收益（$\\beta = 2.0$，$d_0 = 0.5$）")
    ax2.legend(loc="lower left", fontsize=8, framealpha=0.9)
    ax2.set_xlim(0.5, section["g"] + 0.5)
    ax2.set_xticks(rounds)
    fig.tight_layout(w_pad=3, rect=[0, 0.08, 1, 1])
    savefig(fig, "fig_staking_analysis_v2.png")
    print("  -> 图11/fig_staking_analysis_v2.png 已生成")


def fig_timeline():
    fig, ax = plt.subplots(figsize=(12, 5.2))
    section = DATA["timeline"]
    t_exec = section["t_exec"]
    t_slot = section["t_slot"]
    gamma = section["gamma"]
    t_seg = section["t_seg"]
    eta = section["eta"]
    t_reexec = section["t_reexec"]
    c_clever, c_bold, c_cartesi, c_truebit, c_classic = COLORS["dark_orange"], COLORS["orange"], COLORS["gold"], COLORS["cyan_blue"], COLORS["light_blue"]
    c_replay, c_dispute, c_conc = COLORS["gold"], COLORS["orange"], COLORS["cyan_blue"]
    colors = [c_clever, c_bold, c_cartesi, c_truebit, c_classic]
    schemes = [(item["name"], color, item["dispute_slots"] * t_slot) for item, color in zip(section["schemes"], colors)]
    h = 0.45
    totals = []
    for y in range(1, len(schemes)):
        name, color, disp_t = schemes[y]
        left = 0.0
        ax.barh(y, t_exec, h, left=left, color=color, alpha=0.45, edgecolor="white", linewidth=0.6)
        left += t_exec
        ax.barh(y, gamma, h, left=left, color=c_replay, edgecolor=color, linewidth=0.8, alpha=0.85)
        left += gamma
        ax.barh(y, disp_t, h, left=left, color=c_dispute, edgecolor=color, linewidth=0.8, alpha=0.85)
        left += disp_t
        ax.barh(y, t_reexec, h, left=left, color=color, alpha=0.3, hatch="///", edgecolor=color, linewidth=0.6)
        left += t_reexec
        totals.append(left)

    c0 = c_clever
    exec_end = eta * t_exec + t_seg
    ax.barh(0, exec_end, h, left=0, color=c0, alpha=0.45, edgecolor="white", linewidth=0.6)
    cv_y = 0.32
    ax.barh(cv_y, exec_end - t_seg, 0.14, left=t_seg, color=c_conc, alpha=0.85, edgecolor=COLORS["dark_blue"], linewidth=0.7)
    ax.text(t_seg + (exec_end - t_seg) / 2, cv_y, "并发验证", ha="center", va="center", fontsize=7.5, color=COLORS["navy"], fontweight="bold")
    left = exec_end
    ax.barh(0, schemes[0][2], h, left=left, color=c_dispute, edgecolor=c0, linewidth=0.8, alpha=0.85)
    left += schemes[0][2]
    ax.barh(0, t_reexec, h, left=left, color=c0, alpha=0.3, hatch="///", edgecolor=c0, linewidth=0.6)
    left += t_reexec
    totals.insert(0, left)

    ax.axvline(x=eta, color=COLORS["dark_orange"], linewidth=1.5, linestyle=":", alpha=0.8, zorder=10)
    ax.text(eta + 0.03, -0.55, "错误注入\n（$\\eta = 0.4$）", ha="left", va="center", fontsize=8.5, color=COLORS["dark_orange"], fontweight="bold")
    for y, total in enumerate(totals):
        ax.plot(total, y, "k|", markersize=10, markeredgewidth=1.8)
        ax.text(total + 0.04, y, f"{total:.2f} $T_{{\\mathrm{{exec}}}}$", va="center", fontsize=9.5, fontweight="bold", color=schemes[y][1])
    ax.set_yticks(range(len(schemes)))
    ax.set_yticklabels([s[0] for s in schemes], fontsize=9.5)
    ax.set_xlabel("归一化时间（$t / T_{exec}$）", fontsize=10)
    ax.set_title("验证时间线比较\n（DP-Large，错误位置 $\\eta = 0.4$）", fontsize=10.5, fontweight="bold")
    ax.set_xlim(-0.08, max(totals) + 0.45)
    ax.invert_yaxis()
    ax.set_ylim(len(schemes) - 0.4, -0.75)
    ax.grid(True, axis="x", alpha=0.25, linewidth=0.5)
    ax.grid(False, axis="y")
    legend_elements = [
        Patch(facecolor=c_classic, alpha=0.45, label="执行阶段"),
        Patch(facecolor=c_conc, alpha=0.85, label="并发验证"),
        Patch(facecolor=c_replay, alpha=0.85, label="事后回放与挑战"),
        Patch(facecolor=c_dispute, alpha=0.85, label="争议裁决"),
        Patch(facecolor=COLORS["dark_blue"], alpha=0.3, hatch="///", edgecolor=COLORS["dark_blue"], label="重执行"),
    ]
    ax.legend(handles=legend_elements, loc="upper right", fontsize=8.5, framealpha=0.95, ncol=1, borderpad=0.6, labelspacing=0.5, bbox_to_anchor=(0.98, 0.98))
    fig.tight_layout()
    savefig(fig, "fig_timeline_v3.png")
    print("  -> 图12/fig_timeline_v3.png 已生成")


def main():
    print("正在使用合并脚本从实验数据生成第三章图7-图12...")
    fig_budget_compliance()
    fig_overhead()
    plot_param_sensitivity("parameter_sensitivity", "fig_param_sensitivity_v2.png", "  -> 图9/fig_param_sensitivity_v2.png 已生成")
    fig_gas_comparison()
    fig_staking_analysis()
    fig_timeline()
    print(f"所有图形已保存到 {OUT_DIR}/")


if __name__ == "__main__":
    main()
